#!/bin/bash

echo "🚀 ComideX Tablet - Build APK com Hot Reload"
echo "============================================"
echo ""
echo "📋 Checklist:"
echo "✅ expo-dev-client instalado"
echo "✅ expo-updates configurado"
echo "✅ eas.json preparado"
echo "✅ metro.config.js configurado"
echo ""
echo "🔧 Você precisa ter instalado localmente:"
echo "1. Node.js"
echo "2. EAS CLI (npm install -g eas-cli)"
echo "3. Conta Expo (https://expo.dev)"
echo ""
echo "📱 Para gerar o APK, execute:"
echo ""
echo "1. Clone este projeto para sua máquina local"
echo "2. Entre na pasta TABLET"
echo "3. Execute: npm install"
echo "4. Execute: eas login"
echo "5. Execute: eas build --profile development --platform android"
echo ""
echo "💡 Após instalar o APK no tablet:"
echo "1. Mantenha este servidor rodando: npx expo start --tunnel"
echo "2. Configure o Debug Server Host no app (shake o tablet)"
echo "3. O app vai atualizar automaticamente quando você salvar mudanças!"
echo ""
echo "📖 Veja BUILD_APK_INSTRUCTIONS.md para instruções completas"