#!/bin/bash

# Script para registrar quais produtos precisam de imagens
# Este arquivo lista todos os produtos e seus prompts de busca

echo "📝 Lista de produtos para geração de imagens"
echo "=============================================="
echo ""
echo "Total de produtos únicos: 101"
echo ""
echo "Categorias:"
echo "- Niguiri (6 tipos)"
echo "- Sashimi (5 tipos)"
echo "- Temaki (7 tipos)"
echo "- Uramaki (11 tipos)"  
echo "- Maki/Acelgamaki (7 tipos)"
echo "- Hot Roll (6 tipos)"
echo "- Harumaki (4 tipos)"
echo "- Joe (6 tipos)"
echo "- Carpaccio (4 tipos)"
echo "- Ceviche (2 tipos)"
echo "- Chapa (6 tipos)"
echo "- Guioza (2 tipos)"
echo "- Pastel (3 tipos)"
echo "- Tempura (2 tipos)"
echo "- MAAD Especiais (7 tipos)"
echo "- Sobremesas (4 tipos)"
echo "- Pratos/Porções (6 tipos)"
echo "- Outros (13 tipos)"
echo ""
echo "✅ Use o arquivo /tmp/unique-products.txt para a lista completa"
echo "📂 Imagens serão salvas em: attached_assets/product_images/"
