import { createClient } from '@supabase/supabase-js';

// Initialize Supabase client
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
const supabase = createClient(supabaseUrl, supabaseKey);

const printerProfiles = [
  // EPSON - Líder mundial em impressoras térmicas
  {
    name: 'Epson TM-T88VI',
    manufacturer: 'Epson',
    model: 'TM-T88VI',
    connection_type: 'network',
    paper_width: 80,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC437',
    supports_cut: true,
    cut_command: 'GS V 0',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },
  {
    name: 'Epson TM-T20X',
    manufacturer: 'Epson',
    model: 'TM-T20X',
    connection_type: 'usb',
    paper_width: 80,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC437',
    supports_cut: true,
    cut_command: 'GS V 0',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },
  {
    name: 'Epson TM-T70II',
    manufacturer: 'Epson',
    model: 'TM-T70II',
    connection_type: 'network',
    paper_width: 80,
    dpi: 180,
    charset: 'CP850',
    code_table: 'PC437',
    supports_cut: true,
    cut_command: 'GS V 0',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },
  {
    name: 'Epson TM-U220B',
    manufacturer: 'Epson',
    model: 'TM-U220B',
    connection_type: 'serial',
    paper_width: 80,
    dpi: 180,
    charset: 'CP850',
    code_table: 'PC437',
    supports_cut: false,
    cut_command: '',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },

  // BEMATECH - Marca nacional muito popular
  {
    name: 'Bematech MP-4200 TH',
    manufacturer: 'Bematech',
    model: 'MP-4200 TH',
    connection_type: 'usb',
    paper_width: 80,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC850',
    supports_cut: true,
    cut_command: 'ESC m',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },
  {
    name: 'Bematech MP-5100 TH',
    manufacturer: 'Bematech',
    model: 'MP-5100 TH',
    connection_type: 'network',
    paper_width: 112,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC850',
    supports_cut: true,
    cut_command: 'ESC m',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },
  {
    name: 'Bematech MP-2800 TH',
    manufacturer: 'Bematech',
    model: 'MP-2800 TH',
    connection_type: 'usb',
    paper_width: 80,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC850',
    supports_cut: true,
    cut_command: 'ESC m',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },

  // ELGIN - Marca nacional forte
  {
    name: 'Elgin i9',
    manufacturer: 'Elgin',
    model: 'i9',
    connection_type: 'usb',
    paper_width: 80,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC437',
    supports_cut: true,
    cut_command: 'GS V 0',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },
  {
    name: 'Elgin i8',
    manufacturer: 'Elgin',
    model: 'i8',
    connection_type: 'usb',
    paper_width: 80,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC437',
    supports_cut: true,
    cut_command: 'GS V 0',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },
  {
    name: 'Elgin i7 Plus',
    manufacturer: 'Elgin',
    model: 'i7 Plus',
    connection_type: 'usb',
    paper_width: 80,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC437',
    supports_cut: true,
    cut_command: 'GS V 0',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },
  {
    name: 'Elgin Vox+',
    manufacturer: 'Elgin',
    model: 'Vox+',
    connection_type: 'network',
    paper_width: 80,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC437',
    supports_cut: true,
    cut_command: 'GS V 0',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },

  // STAR MICRONICS - Popular mundialmente
  {
    name: 'Star TSP143III',
    manufacturer: 'Star Micronics',
    model: 'TSP143III',
    connection_type: 'network',
    paper_width: 80,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC437',
    supports_cut: true,
    cut_command: 'ESC d 0',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },
  {
    name: 'Star TSP650II',
    manufacturer: 'Star Micronics',
    model: 'TSP650II',
    connection_type: 'network',
    paper_width: 80,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC437',
    supports_cut: true,
    cut_command: 'ESC d 0',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },
  {
    name: 'Star mC-Print3',
    manufacturer: 'Star Micronics',
    model: 'mC-Print3',
    connection_type: 'network',
    paper_width: 80,
    dpi: 203,
    charset: 'UTF-8',
    code_table: 'UTF-8',
    supports_cut: true,
    cut_command: 'ESC d 0',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },

  // DARUMA - Nacional
  {
    name: 'Daruma DR800',
    manufacturer: 'Daruma',
    model: 'DR800',
    connection_type: 'usb',
    paper_width: 80,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC850',
    supports_cut: true,
    cut_command: 'ESC m',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },
  {
    name: 'Daruma DR700',
    manufacturer: 'Daruma',
    model: 'DR700',
    connection_type: 'usb',
    paper_width: 80,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC850',
    supports_cut: true,
    cut_command: 'ESC m',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },

  // SWEDA - Nacional
  {
    name: 'Sweda SI-300S',
    manufacturer: 'Sweda',
    model: 'SI-300S',
    connection_type: 'usb',
    paper_width: 80,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC850',
    supports_cut: true,
    cut_command: 'GS V 0',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },
  {
    name: 'Sweda SI-250',
    manufacturer: 'Sweda',
    model: 'SI-250',
    connection_type: 'usb',
    paper_width: 58,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC850',
    supports_cut: true,
    cut_command: 'GS V 0',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },

  // TANCA - Nacional
  {
    name: 'Tanca TP-650',
    manufacturer: 'Tanca',
    model: 'TP-650',
    connection_type: 'usb',
    paper_width: 80,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC437',
    supports_cut: true,
    cut_command: 'GS V 0',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },
  {
    name: 'Tanca TMP-500',
    manufacturer: 'Tanca',
    model: 'TMP-500',
    connection_type: 'usb',
    paper_width: 58,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC437',
    supports_cut: true,
    cut_command: 'GS V 0',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },

  // DIEBOLD NIXDORF
  {
    name: 'Diebold IM453HU',
    manufacturer: 'Diebold Nixdorf',
    model: 'IM453HU',
    connection_type: 'usb',
    paper_width: 80,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC437',
    supports_cut: true,
    cut_command: 'GS V 0',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },
  {
    name: 'Diebold IM433TD',
    manufacturer: 'Diebold Nixdorf',
    model: 'IM433TD',
    connection_type: 'usb',
    paper_width: 80,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC437',
    supports_cut: true,
    cut_command: 'GS V 0',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },

  // CONTROL ID
  {
    name: 'Control iD Print iD',
    manufacturer: 'Control iD',
    model: 'Print iD',
    connection_type: 'usb',
    paper_width: 80,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC437',
    supports_cut: true,
    cut_command: 'GS V 0',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },
  {
    name: 'Control iD Print iD Touch',
    manufacturer: 'Control iD',
    model: 'Print iD Touch',
    connection_type: 'network',
    paper_width: 80,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC437',
    supports_cut: true,
    cut_command: 'GS V 0',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },

  // JETWAY
  {
    name: 'Jetway JP-500',
    manufacturer: 'Jetway',
    model: 'JP-500',
    connection_type: 'usb',
    paper_width: 58,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC437',
    supports_cut: true,
    cut_command: 'GS V 0',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },
  {
    name: 'Jetway JP-800',
    manufacturer: 'Jetway',
    model: 'JP-800',
    connection_type: 'usb',
    paper_width: 80,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC437',
    supports_cut: true,
    cut_command: 'GS V 0',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },

  // GERTEC
  {
    name: 'Gertec G250',
    manufacturer: 'Gertec',
    model: 'G250',
    connection_type: 'usb',
    paper_width: 80,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC850',
    supports_cut: true,
    cut_command: 'ESC m',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },

  // DATAREGIS (Marca nacional)
  {
    name: 'Dataregis EP-26',
    manufacturer: 'Dataregis',
    model: 'EP-26',
    connection_type: 'usb',
    paper_width: 80,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC850',
    supports_cut: true,
    cut_command: 'GS V 0',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },

  // CITIZEN
  {
    name: 'Citizen CT-S310II',
    manufacturer: 'Citizen',
    model: 'CT-S310II',
    connection_type: 'usb',
    paper_width: 80,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC437',
    supports_cut: true,
    cut_command: 'GS V 0',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },
  {
    name: 'Citizen CT-E651',
    manufacturer: 'Citizen',
    model: 'CT-E651',
    connection_type: 'network',
    paper_width: 80,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC437',
    supports_cut: true,
    cut_command: 'GS V 0',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },

  // ZEBRA
  {
    name: 'Zebra ZD220',
    manufacturer: 'Zebra',
    model: 'ZD220',
    connection_type: 'usb',
    paper_width: 80,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC437',
    supports_cut: false,
    cut_command: '',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  },

  // SAM4S
  {
    name: 'SAM4S GIANT-100',
    manufacturer: 'SAM4S',
    model: 'GIANT-100',
    connection_type: 'network',
    paper_width: 80,
    dpi: 203,
    charset: 'CP850',
    code_table: 'PC437',
    supports_cut: true,
    cut_command: 'GS V 0',
    default_font_size: 1,
    default_font_type: 'A',
    line_spacing: 30,
    margin_left: 0,
    margin_right: 0,
    margin_top: 0,
    margin_bottom: 0,
    custom_commands: {},
    active: true
  }
];

async function seedPrinterProfiles() {
  console.log('🖨️ Iniciando inserção de perfis de impressoras...');

  for (const profile of printerProfiles) {
    try {
      // Check if profile already exists
      const { data: existing } = await supabase
        .from('printer_profiles')
        .select('id')
        .eq('name', profile.name)
        .single();

      if (existing) {
        console.log(`⏭️ Perfil "${profile.name}" já existe, pulando...`);
        continue;
      }

      // Insert the profile
      const { data, error } = await supabase
        .from('printer_profiles')
        .insert(profile)
        .select()
        .single();

      if (error) {
        console.error(`❌ Erro ao inserir perfil "${profile.name}":`, error);
      } else {
        console.log(`✅ Perfil "${profile.name}" inserido com sucesso!`);
        
        // Create default templates for each profile
        const templates = [
          {
            profile_id: data.id,
            template_type: 'receipt',
            name: 'Cupom Fiscal Padrão',
            description: 'Template padrão para cupom fiscal',
            header_enabled: true,
            header_align: 'center',
            header_bold: true,
            header_size: 2,
            body_font_size: 1,
            body_line_spacing: 30,
            body_align: 'left',
            footer_enabled: true,
            footer_align: 'center',
            footer_text: 'Obrigado pela preferência!',
            items_columns: ['nome', 'qtd', 'valor'],
            items_column_widths: { nome: 50, qtd: 20, valor: 30 },
            show_logo: false,
            logo_path: '',
            show_qrcode: false,
            show_barcode: false,
            barcode_type: 'CODE128',
            barcode_height: 50,
            barcode_width: 2,
            cut_paper: true,
            cut_type: 'partial',
            feed_lines_before: 0,
            feed_lines_after: 3,
            open_drawer: false,
            custom_header: '',
            custom_footer: '',
            active: true
          },
          {
            profile_id: data.id,
            template_type: 'kitchen',
            name: 'Comanda Cozinha',
            description: 'Template para pedidos da cozinha',
            header_enabled: true,
            header_align: 'center',
            header_bold: true,
            header_size: 3,
            body_font_size: 2,
            body_line_spacing: 35,
            body_align: 'left',
            footer_enabled: false,
            footer_align: 'center',
            footer_text: '',
            items_columns: ['qtd', 'nome', 'obs'],
            items_column_widths: { qtd: 15, nome: 60, obs: 25 },
            show_logo: false,
            logo_path: '',
            show_qrcode: false,
            show_barcode: false,
            barcode_type: 'CODE128',
            barcode_height: 50,
            barcode_width: 2,
            cut_paper: true,
            cut_type: 'full',
            feed_lines_before: 2,
            feed_lines_after: 5,
            open_drawer: false,
            custom_header: '',
            custom_footer: '',
            active: true
          }
        ];

        for (const template of templates) {
          const { error: templateError } = await supabase
            .from('print_templates')
            .insert(template);
          
          if (templateError) {
            console.error(`   ❌ Erro ao criar template "${template.name}":`, templateError);
          } else {
            console.log(`   📄 Template "${template.name}" criado`);
          }
        }
      }
    } catch (err) {
      console.error(`❌ Erro ao processar perfil "${profile.name}":`, err);
    }
  }

  console.log('✨ Processo de inserção de perfis concluído!');
}

// Run the seeder
seedPrinterProfiles().catch(console.error);